In [3]:
import pandas as pd

In [4]:
#data = pd.read_excel("/home/centos/Documents/admission_analysis/回归分析两独热+哈希编码版.xlsx")
data = pd.read_excel("/Users/ichigo34/Downloads/2.招生数据分析项目/回归分析/回归分析两独热+哈希编码版.xlsx")

In [5]:
import numpy as np

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X = data.iloc[:,1:98]

In [7]:
X

col_0  col_1  col_2  col_3  col_4  col_5  col_6  col_7  招生年度  性别  ...  \
0           0      0      1      0      0      1      0      1  2016   0  ...   
1           0      0      0      0      1      1      0      1  2016   0  ...   
2           0      0      0      0      0      0      1      2  2016   1  ...   
3           0      0      1      0      0      0      1      1  2016   1  ...   
4           0      0      1      1      0      1      0      0  2016   1  ...   
...       ...    ...    ...    ...    ...    ...    ...    ...   ...  ..  ...   
113676      2      0      0      0      0      0      1      0  2018   1  ...   
113677      0      0      0      2      0      0      0      1  2018   1  ...   
113678      1      1      0      0      1      0      0      0  2018   0  ...   
113679      0      1      0      0      0      0      2      0  2018   0  ...   
113680      1      0      0      0      0      0      1      1  2018   1  ...   

        户口所在地-贵州省  户口所在地-辽宁省  户口所在地-重庆市  户口所在地-陕西省  户口所在地-青海省  户口所在地-香港特别行政区  \
0               0          0          0          0          0              0   
1               0          0          0          0          0              0   
2               0          0          0          0          0              0   
3               0          0          0          0          0              0   
4               0          0          0          0          0              0   
...           ...        ...        ...        ...        ...            ...   
113676          0          0          0          0          0              0   
113677          0          0          0          0          0              0   
113678          0          0          0          0          0              0   
113679          0          0          0          0          0              0   
113680          0          0          0          0          0              0   

        户口所在地-黑龙江省  考试科目数量  考试大致难度  计划录取人数  
0                0       3       5      10  
1                0       3       5      10  
2                1       3       4      70  
3                0       2       3      20  
4                0       2       3      45  
...            ...     ...     ...     ...  
113676           0       3       6      18  
113677           0       1       5      15  
113678           0       4       7      15  
113679           0       4       7      50  
113680           0       3       5      20  

[113681 rows x 97 columns]

In [8]:
y = data['是否发放合格证']

In [9]:
x_train, x_test, y_train, y_test = train_test_split(X,y,train_size = 0.8 , test_size = 0.2 , stratify = y)

In [10]:
from sklearn.linear_model import LogisticRegression

In [11]:
log_reg = LogisticRegression()
log_reg.fit(x_train, y_train)

#LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
#          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
#          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
#          verbose=0, warm_start=False)

/Users/ichigo34/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [12]:
log_reg.score(x_train, y_train)

0.965341308937368

In [13]:
y_predict = log_reg.predict(x_test)

In [14]:
log_reg.score(x_test, y_predict)

1.0

In [15]:
log_reg.score(x_test, y_test)

0.9653428332673616

In [16]:
from sklearn.metrics import r2_score

In [17]:
print("训练集合上R^2 = {:.3f}".format(log_reg.score(x_train, y_train)))
print("测试集合上R^2 = {:.3f} ".format(log_reg.score(x_test, y_test)))

训练集合上R^2 = 0.965
测试集合上R^2 = 0.965 


In [18]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_predict))

from sklearn.metrics import precision_score
print(precision_score(y_test,y_predict))

from sklearn.metrics import  recall_score
print(recall_score(y_test,y_predict))

[[21949     0]
 [  788     0]]
0.0
0.0


/Users/ichigo34/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [19]:
import imbalanced_ensemble as imbens

In [11]:
# Import utilities
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_moons, make_circles, make_classification
from imbalanced_ensemble.datasets import make_imbalance

# Import plot utilities
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

RANDOM_STATE = 42


In [12]:
from imbalanced_ensemble.utils.testing import all_estimators

init_kwargs = {'n_estimators': 5, 'random_state': RANDOM_STATE}
all_ensembles_clf = {name: ensemble(**init_kwargs) for (name, ensemble) in all_estimators('ensemble')}

print ('{:<30s} | Class \n{:=<120s}'.format('Method', ''))
for (name, ensemble) in all_estimators('ensemble'):
    print ('{:<30s} | {}'.format(name, ensemble))

Method                         | Class 
AdaCostClassifier              | <class 'imbalanced_ensemble.ensemble.reweighting.adacost.AdaCostClassifier'>
AdaUBoostClassifier            | <class 'imbalanced_ensemble.ensemble.reweighting.adauboost.AdaUBoostClassifier'>
AsymBoostClassifier            | <class 'imbalanced_ensemble.ensemble.reweighting.asymmetric_boost.AsymBoostClassifier'>
BalanceCascadeClassifier       | <class 'imbalanced_ensemble.ensemble.under_sampling.balance_cascade.BalanceCascadeClassifier'>
BalancedRandomForestClassifier | <class 'imbalanced_ensemble.ensemble.under_sampling.balanced_random_forest.BalancedRandomForestClassifier'>
CompatibleAdaBoostClassifier   | <class 'imbalanced_ensemble.ensemble.compatible.adaboost_compatible.CompatibleAdaBoostClassifier'>
CompatibleBaggingClassifier    | <class 'imbalanced_ensemble.ensemble.compatible.bagging_compatible.CompatibleBaggingClassifier'>
EasyEnsembleClassifier         | <class 'imbalanced_ensemble.ensemble.under_sampling

In [26]:
from imbalanced_ensemble.ensemble.under_sampling.__init__ import __all__ as names

classifiers = [all_ensembles_clf[name] for name in names]
for name, clf in zip(names, classifiers):
    print(name)
    clf.fit(x_train, y_train)
    #score = sklearn.metrics.average_precision_score(y_test, clf.predict(x_test))
    print(confusion_matrix(y_test,clf.predict(x_test)))

    from sklearn.metrics import precision_score
    print(precision_score(y_test,clf.predict(x_test)))

    from sklearn.metrics import  recall_score
    print(recall_score(y_test,clf.predict(x_test)))

#plot_classifier_comparison(classifiers, names, datasets, figsize=(len(names)*3+3, 9))

SelfPacedEnsembleClassifier
[[14513  7436]
 [  228   560]]
0.07003501750875438
0.7106598984771574
BalanceCascadeClassifier
[[14711  7238]
 [  289   499]]
0.06449528240920253
0.633248730964467
BalancedRandomForestClassifier
[[14703  7246]
 [  236   552]]
0.07078738137984099
0.700507614213198
EasyEnsembleClassifier
[[15671  6278]
 [  258   530]]
0.07784958871915394
0.6725888324873096
RUSBoostClassifier
[[16958  4991]
 [  331   457]]
0.08388399412628487
0.5799492385786802
UnderBaggingClassifier
[[16677  5272]
 [  333   455]]
0.07944822769338222
0.5774111675126904


In [27]:
from imbalanced_ensemble.ensemble.over_sampling.__init__ import __all__ as names_os

classifiers_os = [all_ensembles_clf[name] for name in names_os]
for name, clf in zip(names_os, classifiers_os):
    if(name == 'KmeansSMOTEBoostClassifier'): continue
    print(name)
    clf.fit(x_train, y_train)
    #score = sklearn.metrics.average_precision_score(y_test, clf.predict(x_test))
    print(confusion_matrix(y_test,clf.predict(x_test)))

    from sklearn.metrics import precision_score
    print(precision_score(y_test,clf.predict(x_test)))

    from sklearn.metrics import  recall_score
    print(recall_score(y_test,clf.predict(x_test)))

#plot_classifier_comparison(classifiers, names, datasets, figsize=(len(names)*3+3, 9))

OverBoostClassifier
[[17251  4698]
 [  347   441]]
0.08581436077057793
0.5596446700507615
SMOTEBoostClassifier
[[14326  7623]
 [  248   540]]
0.06615214994487321
0.6852791878172588
OverBaggingClassifier
[[21560   389]
 [  734    54]]
0.12189616252821671
0.06852791878172589
SMOTEBaggingClassifier
[[21467   482]
 [  729    59]]
0.10905730129390019
0.07487309644670051


In [28]:
from imbalanced_ensemble.ensemble.reweighting.__init__ import __all__ as names_r

classifiers_r = [all_ensembles_clf[name] for name in names_r]
for name, clf in zip(names_os, classifiers_r):
    print(name)
    clf.fit(x_train, y_train)
    #score = sklearn.metrics.average_precision_score(y_test, clf.predict(x_test))
    print(confusion_matrix(y_test,clf.predict(x_test)))

    from sklearn.metrics import precision_score
    print(precision_score(y_test,clf.predict(x_test)))

    from sklearn.metrics import  recall_score
    print(recall_score(y_test,clf.predict(x_test)))

#plot_classifier_comparison(classifiers, names, datasets, figsize=(len(names)*3+3, 9))

OverBoostClassifier
[[21949     0]
 [  788     0]]
0.0
0.0
SMOTEBoostClassifier


/Users/ichigo34/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[17251  4698]
 [  347   441]]
0.08581436077057793
0.5596446700507615
KmeansSMOTEBoostClassifier
[[21761   188]
 [  754    34]]
0.15315315315315314
0.04314720812182741


In [56]:
import math

In [57]:
from imbalanced_ensemble.ensemble.under_sampling.__init__ import __all__ as names_us

classifiers_us = [all_ensembles_clf[name] for name in names_us]
for name, clf in zip(names_us, classifiers_us):
    print(name)
    clf.fit(x_train, y_train)
    #score = sklearn.metrics.average_precision_score(y_test, clf.predict(x_test))

    from sklearn.metrics import precision_score
    print(precision_score(y_test,clf.predict(x_test)))

    from sklearn.metrics import  recall_score
    recall_score = recall_score(y_test,clf.predict(x_test))
    print(recall_score)
    
    c_m  = confusion_matrix(y_test,clf.predict(x_test))
    #print(c_m)
    tn, fp, fn, tp = c_m.ravel()
    #print(c_m.ravel())
    specificity = tn / (tn+fp)
    print(specificity)
    
    print(math.sqrt(specificity * recall_score))
    print(" ")

#plot_classifier_comparison(classifiers, names, datasets, figsize=(len(names)*3+3, 9))

SelfPacedEnsembleClassifier
0.0675761825831952
0.6725888324873096
0.6668185338739806
0.6696974683983807
 
BalanceCascadeClassifier
0.06572893387669251
0.6345177664974619
0.6762039272859811
0.6550293166250751
 
BalancedRandomForestClassifier
0.07078738137984099
0.700507614213198
0.6698710647409905
0.6850180883685962
 
EasyEnsembleClassifier
0.07784958871915394
0.6725888324873096
0.7139733017449542
0.6929721996211308
 
RUSBoostClassifier
0.08388399412628487
0.5799492385786802
0.7726092304888605
0.6693833990628052
 
UnderBaggingClassifier


KeyboardInterrupt: 

In [53]:
data_inv = pd.read_excel("/Users/ichigo34/Downloads/2.招生数据分析项目/回归分析/回归分析两独热+哈希编码版_反转版.xlsx")

In [54]:
X_inv = data.iloc[:,1:98]
y_inv = data['是否发放合格证']
x_train_inv, x_test_inv, y_train_inv, y_test_inv = train_test_split(X_inv,y_inv,train_size = 0.8 , test_size = 0.2 , stratify = y_inv)

In [110]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn import metrics

In [100]:
import os

In [79]:
def sensitivity_my(tp,fn):
    return tp / (tp + fn)

In [80]:
def specificity_my(tn,fp):
    return tn / (tn + fp)

In [81]:
def kappa(tp,tn,fp,fn):
    total_accuracy = (tp + tn)/(tp + tn + fp + fn)
    random_accuracy = ((tn + fp) * (tn + fn) + (fn + tp) * (fp + tp))/((tp + tn + fp + fn)  * (tp + tn + fp + fn))
    return (total_accuracy - random_accuracy)/(1 - random_accuracy)

In [82]:
def Youden_Index(tn,tp,fn,fp):
    ans = sensitivity_my(tp,fn) - 1.0 + specificity_my(tn,fp)
    return ans

In [83]:
def g_mean(tn,tp,fn,fp):
    return math.sqrt(sensitivity_my(tp,fn) * specificity_my(tn,fp))

In [91]:
def mcc(tn,tp,fn,fp):
    ans = (tp * tn - fp * fn)/math.sqrt((tp + fp) * (tp + fn) * (tn + fp) * (tn + fn))
    return ans

In [85]:
def balanced_accuracy(tn,tp,fn,fp):
    ans = 0.5 * sensitivity_my(tp,fn) * specificity_my(tn,fp)
    return ans

In [86]:
def precision(tp,fp):
    return tp / (tp + fp)

In [105]:
def f_measure(tn,tp,fn,fp):
    up = 2.0 * sensitivity_my(tp,fn) * precision(tp,fp)
    down = sensitivity_my(tp,fn) + precision(tp,fp)
    return up / down

In [106]:
def AFM(tn,tp,fn,fp,tn_i,tp_i,fn_i,fp_i):
    f2 = 5.0 * sensitivity_my(tp,fn) * precision(tp,fp) / (4.0 * sensitivity_my(tp,fn) + precision(tp,fp))
    inv_f = 5.0 / 4.0 * sensitivity_my(tp_i,fn_i) * precision(tp_i,fp_i) / (0.5 * 0.5 * sensitivity_my(tp_i,fn_i) + precision(tp_i,fp_i))
    return math.sqrt(f2 * inv_f)

In [89]:
def lift(tn,tp,fn,fp):
    up = tp / (tp + fp)
    down = (tp + fn) / (tp + tn + fp + fn)
    return up / down

In [111]:
def fpr_my(fp,tn):
    return fp / (fp + tn)

In [126]:
IMBENS_result = pd.read_excel("/Users/ichigo34/Downloads/2.招生数据分析项目/回归分析/IMBENS results.xlsx")

In [129]:
IMBENS_result.iloc[4,1] # 坐上角的空格自动忽略了

3.0

In [141]:
IMBENS_result

Unnamed: 0  precision  recall  kappa  Youden_Index  \
0      SelfPacedEnsembleClassifier        NaN     NaN    NaN           NaN   
1         BalanceCascadeClassifier        NaN     NaN    NaN           NaN   
2   BalancedRandomForestClassifier        NaN     NaN    NaN           NaN   
3           EasyEnsembleClassifier        NaN     NaN    NaN           NaN   
4               RUSBoostClassifier        3.0     NaN    NaN           NaN   
5           UnderBaggingClassifier        NaN     NaN    NaN           NaN   
6              OverBoostClassifier        NaN     NaN    NaN           NaN   
7             SMOTEBoostClassifier        NaN     NaN    NaN           NaN   
8            OverBaggingClassifier        NaN     NaN    NaN           NaN   
9           SMOTEBaggingClassifier        NaN     NaN    NaN           NaN   
10             OverBoostClassifier        NaN     NaN    NaN           NaN   
11            SMOTEBoostClassifier        NaN     NaN    NaN           NaN   
12      KmeansSMOTEBoostClassifier        NaN     NaN    NaN           NaN   

    g_mean  mcc  balanced_accuracy  f_measure  lift  AFM  AUC  
0      NaN  NaN                NaN        NaN   NaN  NaN  NaN  
1      NaN  NaN                NaN        NaN   NaN  NaN  NaN  
2      NaN  NaN                NaN        NaN   NaN  NaN  NaN  
3      NaN  NaN                NaN        NaN   NaN  NaN  NaN  
4      NaN  NaN                NaN        NaN   NaN  NaN  NaN  
5      NaN  NaN                NaN        NaN   NaN  NaN  NaN  
6      NaN  NaN                NaN        NaN   NaN  NaN  NaN  
7      NaN  NaN                NaN        NaN   NaN  NaN  NaN  
8      NaN  NaN                NaN        NaN   NaN  NaN  NaN  
9      NaN  NaN                NaN        NaN   NaN  NaN  NaN  
10     NaN  NaN                NaN        NaN   NaN  NaN  NaN  
11     NaN  NaN                NaN        NaN   NaN  NaN  NaN  
12     NaN  NaN                NaN        NaN   NaN  NaN  NaN

In [158]:
df_IMBENS_result = pd.DataFrame([],
     index=['SelfPacedEnsembleClassifier', 'BalanceCascadeClassifier', 'BalancedRandomForestClassifier'
            ,'EasyEnsembleClassifier','RUSBoostClassifier','UnderBaggingClassifier','OverBoostClassifier',
           'SMOTEBoostClassifier','OverBaggingClassifier','SMOTEBaggingClassifier','AdaCostClassifier',
           'AdaUBoostClassifier','AsymBoostClassifier'],
     columns=['precision', 'recall','kappa','Youden_Index','g_mean','mcc','balanced_accuracy','f_measure','lift','AFM','AUC'])

In [155]:
from imbalanced_ensemble.ensemble.under_sampling.__init__ import __all__ as names_us

for name in names_us:
    print(name)

SelfPacedEnsembleClassifier
BalanceCascadeClassifier
BalancedRandomForestClassifier
EasyEnsembleClassifier
RUSBoostClassifier
UnderBaggingClassifier


In [156]:
from imbalanced_ensemble.ensemble.over_sampling.__init__ import __all__ as names_os

for name in names_os:
    print(name)

OverBoostClassifier
SMOTEBoostClassifier
KmeansSMOTEBoostClassifier
OverBaggingClassifier
SMOTEBaggingClassifier


In [157]:
from imbalanced_ensemble.ensemble.reweighting.__init__ import __all__ as names_r

for name in names_r:
    print(name)

AdaCostClassifier
AdaUBoostClassifier
AsymBoostClassifier


In [160]:
from imbalanced_ensemble.ensemble.under_sampling.__init__ import __all__ as names_us

classifiers_us = [all_ensembles_clf[name] for name in names_us]
for name, clf in zip(names_us, classifiers_us):
    # print(name)
    clf.fit(x_train, y_train)
    #score = sklearn.metrics.average_precision_score(y_test, clf.predict(x_test))
    # print(confusion_matrix(y_test,clf.predict(x_test)))
    y_pred = clf.predict(x_test)
    predict_prob_y = clf.predict_proba(x_test)
    # print("precision: %f" %precision_score(y_test,y_pred))
    df_IMBENS_result.loc[name,'precision'] = precision_score(y_test,y_pred)
    # print("recall: %f" %sklearn.metrics.recall_score(y_test,y_pred))
    df_IMBENS_result.loc[name,'recall'] = sklearn.metrics.recall_score(y_test,y_pred)
    
    c_m  = confusion_matrix(y_test,clf.predict(x_test))
    # print(c_m)
    tn, fp, fn, tp = c_m.ravel()
    # print(c_m.ravel())
    
    clf.fit(x_train_inv, y_train_inv)
    c_m_inv  = confusion_matrix(y_test_inv,clf.predict(x_test_inv))
    # print(c_m)
    tn_i, fp_i, fn_i, tp_i = c_m_inv.ravel()
    # print(c_m.ravel())
    
    # print("kappa: %f" %kappa(tp,tn,fp,fn))
    df_IMBENS_result.loc[name,'kappa'] = kappa(tp,tn,fp,fn)
    
    # print("Youden_Index: %f" %Youden_Index(tn,tp,fn,fp))
    df_IMBENS_result.loc[name,'Youden_Index'] = Youden_Index(tn,tp,fn,fp)
    
    # print("g_mean: %f" %g_mean(tn,tp,fn,fp))
    df_IMBENS_result.loc[name,'g_mean'] = g_mean(tn,tp,fn,fp)
    
    # print("mcc: %f" %mcc(tn,tp,fn,fp))
    df_IMBENS_result.loc[name,'mcc'] = mcc(tn,tp,fn,fp)
    
    # print("balanced_accuracy: %f" %balanced_accuracy(tn,tp,fn,fp))
    df_IMBENS_result.loc[name,'balanced_accuracy'] = balanced_accuracy(tn,tp,fn,fp)
    
    try:
        # print("f_measure: %f" %f_measure(tn,tp,fn,fp))
        df_IMBENS_result.loc[name,'f_measure'] = f_measure(tn,tp,fn,fp)#运行别的代码
    except TypeError:
        print("f_measure: can't calculate")        #如果在try部份引发了'name'异常
    #else:
    
    # print("lift: %f" %lift(tn,tp,fn,fp))
    df_IMBENS_result.loc[name,'lift'] = lift(tn,tp,fn,fp)
    
    try:
        # print("AFM: %f" %AFM(tn,tp,fn,fp,tn_i,tp_i,fn_i,fp_i))        #运行别的代码
        df_IMBENS_result.loc[name,'AFM'] = AFM(tn,tp,fn,fp,tn_i,tp_i,fn_i,fp_i)
    except TypeError:
        print("AFM: can't calculate")
    
    # print("AUC: %f" %metrics.auc(fpr_my(fp,tn),sensitivity_my(tp,fn)))
    df_IMBENS_result.loc[name,'AUC'] = roc_auc_score(y_test,predict_prob_y[:, 1])
    
df_IMBENS_result
#plot_classifier_comparison(classifiers_us, names_us, datasets, figsize=(len(names_us)*3+3, 9))

precision    recall     kappa Youden_Index  \
SelfPacedEnsembleClassifier     0.069248  0.676396  0.066967     0.350003   
BalanceCascadeClassifier        0.065992  0.637056  0.060593     0.313351   
BalancedRandomForestClassifier  0.070787  0.700508  0.070038     0.370379   
EasyEnsembleClassifier           0.07785  0.672589  0.082552     0.386562   
RUSBoostClassifier              0.083884  0.579949  0.091557     0.352558   
UnderBaggingClassifier          0.079448  0.577411  0.083856     0.337218   
OverBoostClassifier             0.085814  0.559645  0.094384     0.345603   
SMOTEBoostClassifier            0.066152  0.685279  0.061321     0.337974   
OverBaggingClassifier           0.121896  0.068528  0.064396     0.050805   
SMOTEBaggingClassifier          0.109057  0.074873  0.062331     0.052913   
AdaCostClassifier                    NaN       NaN       NaN          NaN   
AdaUBoostClassifier                  NaN       NaN       NaN          NaN   
AsymBoostClassifier                  NaN       NaN       NaN          NaN   

                                  g_mean       mcc balanced_accuracy  \
SelfPacedEnsembleClassifier        0.675  0.135287          0.227813   
BalanceCascadeClassifier        0.656382  0.121472          0.215419   
BalancedRandomForestClassifier  0.685018  0.142713          0.234625   
EasyEnsembleClassifier          0.692972  0.154378          0.240105   
RUSBoostClassifier              0.669383  0.151077          0.224037   
UnderBaggingClassifier           0.66236  0.142091           0.21936   
OverBoostClassifier             0.663217  0.151139          0.219929   
SMOTEBoostClassifier            0.668789  0.128866          0.223639   
OverBaggingClassifier           0.259448  0.067233          0.033657   
SMOTEBaggingClassifier          0.270608  0.063504          0.036614   
AdaCostClassifier                    NaN       NaN               NaN   
AdaUBoostClassifier                  NaN       NaN               NaN   
AsymBoostClassifier                  NaN       NaN               NaN   

                               f_measure      lift       AFM       AUC  
SelfPacedEnsembleClassifier     0.125633  1.998079  0.146234  0.728213  
BalanceCascadeClassifier        0.119595  1.904133  0.137982  0.698987  
BalancedRandomForestClassifier  0.128581  2.042503  0.148626  0.735451  
EasyEnsembleClassifier          0.139547  2.246277   0.16394  0.762839  
RUSBoostClassifier              0.146568  2.420394  0.168394  0.720647  
UnderBaggingClassifier          0.139678  2.292404  0.161426  0.738157  
OverBoostClassifier             0.148811  2.476093  0.169635  0.716665  
SMOTEBoostClassifier            0.120657  1.908758  0.140604  0.700022  
OverBaggingClassifier           0.087734  3.517199  0.080251  0.615288  
SMOTEBaggingClassifier          0.088789  3.146746  0.089285   0.62475  
AdaCostClassifier                    NaN       NaN       NaN       NaN  
AdaUBoostClassifier                  NaN       NaN       NaN       NaN  
AsymBoostClassifier                  NaN       NaN       NaN       NaN

In [159]:
from imbalanced_ensemble.ensemble.over_sampling.__init__ import __all__ as names_os

classifiers_os = [all_ensembles_clf[name] for name in names_os]
for name, clf in zip(names_os, classifiers_os):
    if(name == 'KmeansSMOTEBoostClassifier'): continue
    # print(name)
    clf.fit(x_train, y_train)
    #score = sklearn.metrics.average_precision_score(y_test, clf.predict(x_test))
    #print(confusion_matrix(y_test,clf.predict(x_test)))
    y_pred = clf.predict(x_test)
    predict_prob_y = clf.predict_proba(x_test)
    #print("precision: %f" %precision_score(y_test,y_pred))
    df_IMBENS_result.loc[name,'precision'] = precision_score(y_test,y_pred)
    #print("recall: %f" %sklearn.metrics.recall_score(y_test,y_pred))
    df_IMBENS_result.loc[name,'recall'] = sklearn.metrics.recall_score(y_test,y_pred)
    
    c_m  = confusion_matrix(y_test,clf.predict(x_test))
    #print(c_m)
    tn, fp, fn, tp = c_m.ravel()
    #print(c_m.ravel())
    
    clf.fit(x_train_inv, y_train_inv)
    c_m_inv  = confusion_matrix(y_test_inv,clf.predict(x_test_inv))
    #print(c_m)
    tn_i, fp_i, fn_i, tp_i = c_m_inv.ravel()
    #print(c_m.ravel())
    
    #print("kappa: %f" %kappa(tp,tn,fp,fn))
    df_IMBENS_result.loc[name,'kappa'] = kappa(tp,tn,fp,fn)
    
    #print("Youden_Index: %f" %Youden_Index(tn,tp,fn,fp))
    df_IMBENS_result.loc[name,'Youden_Index'] = Youden_Index(tn,tp,fn,fp)
    
    #print("g_mean: %f" %g_mean(tn,tp,fn,fp))
    df_IMBENS_result.loc[name,'g_mean'] = g_mean(tn,tp,fn,fp)
    
    #print("mcc: %f" %mcc(tn,tp,fn,fp))
    df_IMBENS_result.loc[name,'mcc'] = mcc(tn,tp,fn,fp)
    
    #print("balanced_accuracy: %f" %balanced_accuracy(tn,tp,fn,fp))
    df_IMBENS_result.loc[name,'balanced_accuracy'] = balanced_accuracy(tn,tp,fn,fp)
    
    try:
        # print("f_measure: %f" %f_measure(tn,tp,fn,fp))
        df_IMBENS_result.loc[name,'f_measure'] = f_measure(tn,tp,fn,fp)#运行别的代码
    except TypeError:
        print("f_measure: can't calculate")        #如果在try部份引发了'name'异常
    #else:
    
    #print("lift: %f" %lift(tn,tp,fn,fp))
    df_IMBENS_result.loc[name,'lift'] = lift(tn,tp,fn,fp)
    
    try:
        #print("AFM: %f" %AFM(tn,tp,fn,fp,tn_i,tp_i,fn_i,fp_i)) 
        df_IMBENS_result.loc[name,'AFM'] = AFM(tn,tp,fn,fp,tn_i,tp_i,fn_i,fp_i)#运行别的代码
    except TypeError:
        print("AFM: can't calculate")
    
    #print("AUC: %f" %metrics.auc(fpr_my(fp,tn),sensitivity_my(tp,fn)))
    df_IMBENS_result.loc[name,'AUC'] = roc_auc_score(y_test,predict_prob_y[:, 1])
#plot_classifier_comparison(classifiers, names, datasets, figsize=(len(names)*3+3, 9))

df_IMBENS_result

precision    recall     kappa Youden_Index  \
SelfPacedEnsembleClassifier          NaN       NaN       NaN          NaN   
BalanceCascadeClassifier             NaN       NaN       NaN          NaN   
BalancedRandomForestClassifier       NaN       NaN       NaN          NaN   
EasyEnsembleClassifier               NaN       NaN       NaN          NaN   
RUSBoostClassifier                   NaN       NaN       NaN          NaN   
UnderBaggingClassifier               NaN       NaN       NaN          NaN   
OverBoostClassifier             0.085814  0.559645  0.094384     0.345603   
SMOTEBoostClassifier            0.066152  0.685279  0.061321     0.337974   
OverBaggingClassifier           0.121896  0.068528  0.064396     0.050805   
SMOTEBaggingClassifier          0.109057  0.074873  0.062331     0.052913   
AdaCostClassifier                    NaN       NaN       NaN          NaN   
AdaUBoostClassifier                  NaN       NaN       NaN          NaN   
AsymBoostClassifier                  NaN       NaN       NaN          NaN   

                                  g_mean       mcc balanced_accuracy  \
SelfPacedEnsembleClassifier          NaN       NaN               NaN   
BalanceCascadeClassifier             NaN       NaN               NaN   
BalancedRandomForestClassifier       NaN       NaN               NaN   
EasyEnsembleClassifier               NaN       NaN               NaN   
RUSBoostClassifier                   NaN       NaN               NaN   
UnderBaggingClassifier               NaN       NaN               NaN   
OverBoostClassifier             0.663217  0.151139          0.219929   
SMOTEBoostClassifier            0.668789  0.128866          0.223639   
OverBaggingClassifier           0.259448  0.067233          0.033657   
SMOTEBaggingClassifier          0.270608  0.063504          0.036614   
AdaCostClassifier                    NaN       NaN               NaN   
AdaUBoostClassifier                  NaN       NaN               NaN   
AsymBoostClassifier                  NaN       NaN               NaN   

                               f_measure      lift       AFM       AUC  
SelfPacedEnsembleClassifier          NaN       NaN       NaN       NaN  
BalanceCascadeClassifier             NaN       NaN       NaN       NaN  
BalancedRandomForestClassifier       NaN       NaN       NaN       NaN  
EasyEnsembleClassifier               NaN       NaN       NaN       NaN  
RUSBoostClassifier                   NaN       NaN       NaN       NaN  
UnderBaggingClassifier               NaN       NaN       NaN       NaN  
OverBoostClassifier             0.148811  2.476093  0.169635  0.716665  
SMOTEBoostClassifier            0.120657  1.908758  0.140604  0.700022  
OverBaggingClassifier           0.087734  3.517199  0.080251  0.615288  
SMOTEBaggingClassifier          0.088789  3.146746  0.089285   0.62475  
AdaCostClassifier                    NaN       NaN       NaN       NaN  
AdaUBoostClassifier                  NaN       NaN       NaN       NaN  
AsymBoostClassifier                  NaN       NaN       NaN       NaN

In [161]:
from imbalanced_ensemble.ensemble.reweighting.__init__ import __all__ as names_r

classifiers_r = [all_ensembles_clf[name] for name in names_r]
for name, clf in zip(names_r, classifiers_r):
    clf.fit(x_train, y_train)
    y_pred = clf.predict(x_test)
    predict_prob_y = clf.predict_proba(x_test)
    df_IMBENS_result.loc[name,'precision'] = precision_score(y_test,y_pred)
    df_IMBENS_result.loc[name,'recall'] = sklearn.metrics.recall_score(y_test,y_pred)
    
    c_m  = confusion_matrix(y_test,clf.predict(x_test))
    tn, fp, fn, tp = c_m.ravel()
    
    clf.fit(x_train_inv, y_train_inv)
    c_m_inv  = confusion_matrix(y_test_inv,clf.predict(x_test_inv))
    tn_i, fp_i, fn_i, tp_i = c_m_inv.ravel()
    
    df_IMBENS_result.loc[name,'kappa'] = kappa(tp,tn,fp,fn)
    df_IMBENS_result.loc[name,'Youden_Index'] = Youden_Index(tn,tp,fn,fp)
    df_IMBENS_result.loc[name,'g_mean'] = g_mean(tn,tp,fn,fp)
    df_IMBENS_result.loc[name,'mcc'] = mcc(tn,tp,fn,fp)
    df_IMBENS_result.loc[name,'balanced_accuracy'] = balanced_accuracy(tn,tp,fn,fp)
    
    try:
        df_IMBENS_result.loc[name,'f_measure'] = f_measure(tn,tp,fn,fp)
    except TypeError:
        print("f_measure: can't calculate")        #如果在try部份引发了'name'异常
    
    df_IMBENS_result.loc[name,'lift'] = lift(tn,tp,fn,fp)
    
    try:
        df_IMBENS_result.loc[name,'AFM'] = AFM(tn,tp,fn,fp,tn_i,tp_i,fn_i,fp_i)#运行别的代码
    except TypeError:
        print("AFM: can't calculate")
    
    df_IMBENS_result.loc[name,'AUC'] = roc_auc_score(y_test,predict_prob_y[:, 1])

df_IMBENS_result

/Users/ichigo34/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/ichigo34/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
/Users/ichigo34/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in long_scalars
  


precision    recall     kappa Youden_Index  \
SelfPacedEnsembleClassifier     0.069248  0.676396  0.066967     0.350003   
BalanceCascadeClassifier        0.065992  0.637056  0.060593     0.313351   
BalancedRandomForestClassifier  0.070787  0.700508  0.070038     0.370379   
EasyEnsembleClassifier           0.07785  0.672589  0.082552     0.386562   
RUSBoostClassifier              0.083884  0.579949  0.091557     0.352558   
UnderBaggingClassifier          0.079448  0.577411  0.083856     0.337218   
OverBoostClassifier             0.085814  0.559645  0.094384     0.345603   
SMOTEBoostClassifier            0.066152  0.685279  0.061321     0.337974   
OverBaggingClassifier           0.121896  0.068528  0.064396     0.050805   
SMOTEBaggingClassifier          0.109057  0.074873  0.062331     0.052913   
AdaCostClassifier                    0.0       0.0       0.0          0.0   
AdaUBoostClassifier             0.085814  0.559645  0.094384     0.345603   
AsymBoostClassifier             0.153153  0.043147  0.052897     0.034582   

                                  g_mean       mcc balanced_accuracy  \
SelfPacedEnsembleClassifier        0.675  0.135287          0.227813   
BalanceCascadeClassifier        0.656382  0.121472          0.215419   
BalancedRandomForestClassifier  0.685018  0.142713          0.234625   
EasyEnsembleClassifier          0.692972  0.154378          0.240105   
RUSBoostClassifier              0.669383  0.151077          0.224037   
UnderBaggingClassifier           0.66236  0.142091           0.21936   
OverBoostClassifier             0.663217  0.151139          0.219929   
SMOTEBoostClassifier            0.668789  0.128866          0.223639   
OverBaggingClassifier           0.259448  0.067233          0.033657   
SMOTEBaggingClassifier          0.270608  0.063504          0.036614   
AdaCostClassifier                    0.0       NaN               0.0   
AdaUBoostClassifier             0.663217  0.151139          0.219929   
AsymBoostClassifier             0.206828  0.064329          0.021389   

                               f_measure      lift       AFM       AUC  
SelfPacedEnsembleClassifier     0.125633  1.998079  0.146234  0.728213  
BalanceCascadeClassifier        0.119595  1.904133  0.137982  0.698987  
BalancedRandomForestClassifier  0.128581  2.042503  0.148626  0.735451  
EasyEnsembleClassifier          0.139547  2.246277   0.16394  0.762839  
RUSBoostClassifier              0.146568  2.420394  0.168394  0.720647  
UnderBaggingClassifier          0.139678  2.292404  0.161426  0.738157  
OverBoostClassifier             0.148811  2.476093  0.169635  0.716665  
SMOTEBoostClassifier            0.120657  1.908758  0.140604  0.700022  
OverBaggingClassifier           0.087734  3.517199  0.080251  0.615288  
SMOTEBaggingClassifier          0.088789  3.146746  0.089285   0.62475  
AdaCostClassifier                    NaN       NaN       NaN  0.720996  
AdaUBoostClassifier             0.148811  2.476093  0.169473  0.716665  
AsymBoostClassifier             0.067327   4.41909  0.045187  0.718926

In [163]:
df_IMBENS_result.to_excel(r'/Users/ichigo34/Downloads/2.招生数据分析项目/回归分析/IMBENS_result.xlsx', index = True)

In [15]:
from imbalanced_ensemble.ensemble.under_sampling.__init__ import __all__ as names_us

classifiers_eec = all_ensembles_clf['EasyEnsembleClassifier']
classifiers_eec.fit(x_train, y_train)

#特征重要度
features = list(x_test.columns)
importances = classifiers_eec.feature_importances_
indices = np.argsort(importances)[::-1]
num_features = len(importances)
 
#将特征重要度以柱状图展示
plt.figure()
plt.title("Feature importances")
plt.bar(range(num_features), importances[indices], color="b", align="center")
plt.xticks(range(num_features), [features[i] for i in indices], rotation='45')
plt.xlim([-1, num_features])
plt.show()
 
#输出各个特征的重要度
for i in indices:
    print ("{0} - {1:.3f}".format(features[i], importances[i]))

AttributeError: 'EasyEnsembleClassifier' object has no attribute 'feature_importances_'

In [1]:
pip install pdpbox

     |████████████████████████████████| 34.0 MB 217 kB/s eta 0:00:01     |██████████████████▏             | 19.4 MB 209 kB/s eta 0:01:10
     |████████████████████████████████| 14.4 MB 210 kB/s eta 0:00:01
  Created wheel for pdpbox: filename=PDPbox-0.2.1-py3-none-any.whl size=35758226 sha256=1088f15c454d120a7425251e2494a5c139d8dee8c53330995d00b443c99a92a1
  Stored in directory: /Users/ichigo34/Library/Caches/pip/wheels/f4/d0/1a/b80035625c53131f52906a6fc4dd690d8efd2bf8af6a4015eb
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1315 sha256=320db2edfa2ebcd8e60e3d7bbdd6ae02415838ab024b28eebd64ceea8fd7c672
  Stored in directory: /Users/ichigo34/Library/Caches/pip/wheels/46/ef/c3/157e41f5ee1372d1be90b09f74f82b10e391eaacca8f22d33e
Successfully built pdpbox sklearn
ERROR: imbalanced-ensemble 0.1.6 has requirement matplotlib>=3.3.2, but you'll have matplotlib 3.1.1 which is incompatible.
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3

In [2]:
from matplotlib import pyplot as plt
from pdpbox import pdp, get_dataset, info_plots