In [2]:
from sklearn import preprocessing

In [3]:
import category_encoders as ce

In [1]:
import pandas as pd

In [2]:
df_combine = pd.read_excel('/Users/ichigo34/Downloads/2.招生数据分析项目/回归分析/综合信息汇总（第一阶段）.xls',sheet_name = 'combine')

In [3]:
df_test = pd.read_excel('/Users/ichigo34/Downloads/2.招生数据分析项目/回归分析/综合信息汇总（第一阶段）.xls',sheet_name = '考试科目')

In [2]:
import time

In [6]:
time_start = time.time()
for i in range(len(df_combine)):
    for j in range(len(df_test)):
        if df_test.iloc[j,0] == df_combine.iloc[i,1] and df_test.iloc[j,1] == df_combine.iloc[i,5]: # 年份、报考方向一致
            df_combine.iloc[i,19] = df_test.iloc[j,2] # 数目
            df_combine.iloc[i,20] = df_test.iloc[j,3] # 难度
                
time_end = time.time()
print('Time cost = %fs' % (time_end - time_start))

Time cost = 148.011855s


In [7]:
df_combine.to_excel(r'/Users/ichigo34/Downloads/2.招生数据分析项目/回归分析/补全考试科目版.xlsx', index = False)

In [14]:
df_combine = pd.read_excel('/Users/ichigo34/Downloads/2.招生数据分析项目/回归分析/综合信息汇总（第一阶段）.xls',
                           sheet_name = 'combine')

In [15]:
zs_plan = pd.read_excel('/Users/ichigo34/Downloads/2.招生数据分析项目/回归分析/招生计划.xlsx')

In [17]:
time_start = time.time()
for i in range(len(df_combine)):
    for j in range(len(zs_plan)):
        if zs_plan.iloc[j,0] == df_combine.iloc[i,1] and zs_plan.iloc[j,1] == df_combine.iloc[i,5]: # 年份、报考方向一致
            df_combine.iloc[i,23] = zs_plan.iloc[j,2] # 数目
                
time_end = time.time()
print('Time cost = %fs' % (time_end - time_start))

Time cost = 103.953475s


In [18]:
df_combine['计划录取人数']

0         10.0
1          NaN
2          NaN
3          NaN
4          NaN
          ... 
113676     NaN
113677     NaN
113678     NaN
113679     NaN
113680     NaN
Name: 计划录取人数, Length: 113681, dtype: float64

In [20]:
zs_plan.iloc[2,0]


2016

In [21]:
df_combine.iloc[2,1]


2016

In [22]:
zs_plan.iloc[2,1]


'电影学（制片与市场）'

In [23]:
df_combine.iloc[2,5]


'动画'

In [24]:
df_combine.iloc[2,23]


70

In [25]:
zs_plan.iloc[2,2]

45

In [13]:
df_combine.to_excel(r'/Users/ichigo34/Downloads/2.招生数据分析项目/回归分析/补全招生人数版.xlsx', index = False)

In [26]:
from sklearn.preprocessing import OrdinalEncoder

In [27]:
oe = OrdinalEncoder()
oe.fit([ ['ac', 'ef'], 
         ['ef', 'bd'],
         ['gg', 'bd'],
         ['ef', 'ff']]) # 必须是二维

OrdinalEncoder()

In [28]:
print(oe.categories_)

[array(['ac', 'ef', 'gg'], dtype=object), array(['bd', 'ef', 'ff'], dtype=object)]


In [29]:
print(oe.transform([ ['ef', 'ff'],
                     ['gg', 'bd'] ]))

[[1. 2.]
 [2. 0.]]


In [30]:
print( oe.inverse_transform([ [0, 1], 
                              [2, 1],
                              [1, 2] ]))

[['ac' 'ef']
 ['gg' 'ef']
 ['ef' 'ff']]


In [6]:
coding_test = pd.read_excel('/Users/ichigo34/Downloads/2.招生数据分析项目/回归分析/综合信息汇总（第一阶段）.xls')

In [32]:
from sklearn import preprocessing
enc = preprocessing.OneHotEncoder()

In [34]:
data_x = coding_test[['院系','专业','专业方向']]

In [35]:
enc.fit(data_x)

OneHotEncoder()

In [36]:
enc.categories

'auto'

In [38]:
arr = enc.transform(coding_test[['院系','专业','专业方向']]).toarray()

In [39]:
arr

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [40]:
arr.shape

(113681, 63)

In [41]:
enc1 = preprocessing.OneHotEncoder()

In [43]:
enc1.fit(coding_test[['高考所在省']])

OneHotEncoder()

In [44]:
arr1 = enc1.transform(coding_test[['高考所在省']]).toarray()

In [45]:
arr1

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [46]:
arr1.shape

(113681, 36)

In [56]:
enc1.categories

'auto'

In [47]:
enc2 = preprocessing.OneHotEncoder()
enc2.fit(coding_test[['户口所在地']])
arr2 = enc2.transform(coding_test[['户口所在地']]).toarray()
arr2.shape

(113681, 36)

In [48]:
import numpy as np

In [51]:
np.savetxt('001.csv',arr)

In [52]:
np.savetxt('高考所在省.csv',arr1)

In [53]:
np.savetxt('户口所在地.csv',arr2)

In [54]:
enc3 = preprocessing.OneHotEncoder()
enc3.fit(coding_test[['考生类别名称']])
arr3 = enc3.transform(coding_test[['考生类别名称']]).toarray()
arr3.shape
np.savetxt('考生类别名称.csv',arr3)

In [5]:
from category_encoders.hashing import HashingEncoder

In [7]:
y = coding_test[['是否发放合格证']]

In [8]:
he = HashingEncoder(cols=['院系', '专业','专业方向']).fit(coding_test, y)

In [9]:
he.get_feature_names()

['col_0',
 'col_1',
 'col_2',
 'col_3',
 'col_4',
 'col_5',
 'col_6',
 'col_7',
 1,
 '招生年度',
 '性别',
 '年龄',
 '政治面貌名称',
 '民族名称',
 '考生类别名称-农村应届',
 '考生类别名称-农村往届',
 '考生类别名称-城市应届',
 '考生类别名称-城市往届',
 '高考类别',
 '文化程度名称',
 '身高',
 '毕业中学类别',
 '高考所在省-上海市',
 '高考所在省-云南省',
 '高考所在省-内蒙古自治区',
 '高考所在省-北京市',
 '高考所在省-华侨',
 '高考所在省-台湾省',
 '高考所在省-吉林省',
 '高考所在省-四川省',
 '高考所在省-天津市',
 '高考所在省-宁夏回族自治区',
 '高考所在省-安徽省',
 '高考所在省-山东省',
 '高考所在省-山西省',
 '高考所在省-广东省',
 '高考所在省-广西壮族自治区',
 '高考所在省-新疆维吾尔自治区',
 '高考所在省-江苏省',
 '高考所在省-江西省',
 '高考所在省-河北省',
 '高考所在省-河南省',
 '高考所在省-浙江省',
 '高考所在省-海南省',
 '高考所在省-港澳台联招办',
 '高考所在省-湖北省',
 '高考所在省-湖南省',
 '高考所在省-澳门特别行政区',
 '高考所在省-甘肃省',
 '高考所在省-福建省',
 '高考所在省-西藏自治区',
 '高考所在省-贵州省',
 '高考所在省-辽宁省',
 '高考所在省-重庆市',
 '高考所在省-陕西省',
 '高考所在省-青海省',
 '高考所在省-香港特别行政区',
 '高考所在省-黑龙江省',
 '高考所在市',
 '户口所在地-上海市',
 '户口所在地-云南省',
 '户口所在地-内蒙古自治区',
 '户口所在地-北京市',
 '户口所在地-华侨',
 '户口所在地-台湾省',
 '户口所在地-吉林省',
 '户口所在地-四川省',
 '户口所在地-天津市',
 '户口所在地-宁夏回族自治区',
 '户口所在地-安徽省',
 '户口所在地-山东省',
 '户口所在地-山西省',
 '户口所在地-广东省',
 '户口所在地-广西壮族自治区',
 '户口所在地-

In [63]:
data = he.transform(coding_test)
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113681 entries, 0 to 113680
Data columns (total 99 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   col_0           113681 non-null  int64
 1   col_1           113681 non-null  int64
 2   col_2           113681 non-null  int64
 3   col_3           113681 non-null  int64
 4   col_4           113681 non-null  int64
 5   col_5           113681 non-null  int64
 6   col_6           113681 non-null  int64
 7   col_7           113681 non-null  int64
 8   1               113681 non-null  int64
 9   招生年度            113681 non-null  int64
 10  性别              113681 non-null  int64
 11  年龄              113681 non-null  int64
 12  政治面貌名称          113681 non-null  int64
 13  民族名称            113681 non-null  int64
 14  考生类别名称-农村应届     113681 non-null  int64
 15  考生类别名称-农村往届     113681 non-null  int64
 16  考生类别名称-城市应届     113681 non-null  int64
 17  考生类别名称-城市往届     113681 non-null  int64
 18  高考类别

In [64]:
data.to_excel(r'/Users/ichigo34/Downloads/2.招生数据分析项目/回归分析/回归分析两独热+哈希编码版.xlsx', index = False)

In [65]:
hash3 = pd.read_excel('/Users/ichigo34/Downloads/2.招生数据分析项目/回归分析/综合信息汇总（第一阶段）.xls',sheet_name = '原始')

In [66]:
y1 = hash3[['是否发放合格证']]
he1 = HashingEncoder(cols = ['院系', '专业','专业方向']).fit(hash3, y1)
he2 = HashingEncoder(cols = ['高考所在省']).fit(hash3, y1)
he3 = HashingEncoder(cols = ['户口所在地']).fit(hash3, y1)

In [68]:
data1 = he1.transform(hash3)
data2 = he2.transform(hash3)
data3 = he3.transform(hash3)
print(data1.info())
print(data2.info())
print(data3.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113681 entries, 0 to 113680
Data columns (total 29 columns):
 #   Column       Non-Null Count   Dtype 
---  ------       --------------   ----- 
 0   col_0        113681 non-null  int64 
 1   col_1        113681 non-null  int64 
 2   col_2        113681 non-null  int64 
 3   col_3        113681 non-null  int64 
 4   col_4        113681 non-null  int64 
 5   col_5        113681 non-null  int64 
 6   col_6        113681 non-null  int64 
 7   col_7        113681 non-null  int64 
 8   1            113681 non-null  int64 
 9   招生年度         113681 non-null  int64 
 10  性别           113681 non-null  int64 
 11  年龄           113681 non-null  int64 
 12  政治面貌名称       113681 non-null  int64 
 13  民族名称         113681 non-null  int64 
 14  考生类别名称-农村应届  113681 non-null  int64 
 15  考生类别名称-农村往届  113681 non-null  int64 
 16  考生类别名称-城市应届  113681 non-null  int64 
 17  考生类别名称-城市往届  113681 non-null  int64 
 18  高考类别         113681 non-null  int64 
 19  文化

In [3]:
df_1226 = pd.read_excel('/Users/ichigo34/Downloads/2.招生数据分析项目/回归分析/综合信息汇总（处理版）的副本.xls')

In [6]:
df_1226.iloc[20,16]

'三河一中'

In [7]:
time_start = time.time()
for i in range(len(df_1226)):
    if '美术' in df_1226.iloc[i,16]:
        df_1226.iloc[i,17] = 1
                
time_end = time.time()
print('Time cost = %fs' % (time_end - time_start))

Time cost = 2.035773s


In [8]:
time_start = time.time()
for i in range(len(df_1226)):
    if '艺术' in df_1226.iloc[i,16]:
        df_1226.iloc[i,17] = 1
                
time_end = time.time()
print('Time cost = %fs' % (time_end - time_start))

Time cost = 2.137846s


In [9]:
time_start = time.time()
for i in range(len(df_1226)):
    if '演艺' in df_1226.iloc[i,16]:
        df_1226.iloc[i,17] = 1
                
time_end = time.time()
print('Time cost = %fs' % (time_end - time_start))

Time cost = 1.786021s


In [10]:
time_start = time.time()
for i in range(len(df_1226)):
    if '美附中' in df_1226.iloc[i,16]:
        df_1226.iloc[i,17] = 1
                
time_end = time.time()
print('Time cost = %fs' % (time_end - time_start))

Time cost = 1.790414s


In [12]:
time_start = time.time()
for i in range(len(df_1226)):
    if '绘画' in df_1226.iloc[i,16]:
        df_1226.iloc[i,17] = 1
                
time_end = time.time()
print('Time cost = %fs' % (time_end - time_start))

Time cost = 1.781997s


In [13]:
time_start = time.time()
for i in range(len(df_1226)):
    if '音乐' in df_1226.iloc[i,16]:
        df_1226.iloc[i,17] = 1
                
time_end = time.time()
print('Time cost = %fs' % (time_end - time_start))

Time cost = 1.840432s


In [14]:
time_start = time.time()
for i in range(len(df_1226)):
    if '戏曲' in df_1226.iloc[i,16]:
        df_1226.iloc[i,17] = 1
                
time_end = time.time()
print('Time cost = %fs' % (time_end - time_start))

Time cost = 1.845650s


In [15]:
time_start = time.time()
for i in range(len(df_1226)):
    if '戏剧' in df_1226.iloc[i,16]:
        df_1226.iloc[i,17] = 1
                
time_end = time.time()
print('Time cost = %fs' % (time_end - time_start))

Time cost = 1.836421s


In [16]:
time_start = time.time()
for i in range(len(df_1226)):
    if '电影' in df_1226.iloc[i,16]:
        df_1226.iloc[i,17] = 1
                
time_end = time.time()
print('Time cost = %fs' % (time_end - time_start))

Time cost = 1.756530s


In [18]:
time_start = time.time()
for i in range(len(df_1226)):
    if '舞蹈' in df_1226.iloc[i,16]:
        df_1226.iloc[i,17] = 1
                
time_end = time.time()
print('Time cost = %fs' % (time_end - time_start))

Time cost = 1.894178s


In [19]:
time_start = time.time()
for i in range(len(df_1226)):
    if '影视' in df_1226.iloc[i,16]:
        df_1226.iloc[i,17] = 1
                
time_end = time.time()
print('Time cost = %fs' % (time_end - time_start))

Time cost = 1.766686s


In [21]:
time_start = time.time()
for i in range(len(df_1226)):
    if '艺校' in df_1226.iloc[i,16]:
        df_1226.iloc[i,17] = 1
                
time_end = time.time()
print('Time cost = %fs' % (time_end - time_start))

Time cost = 1.780995s


In [22]:
time_start = time.time()
for i in range(len(df_1226)):
    if '上戏' in df_1226.iloc[i,16]:
        df_1226.iloc[i,17] = 1
                
time_end = time.time()
print('Time cost = %fs' % (time_end - time_start))

Time cost = 1.774608s


In [23]:
time_start = time.time()
for i in range(len(df_1226)):
    if '中戏' in df_1226.iloc[i,16]:
        df_1226.iloc[i,17] = 1
                
time_end = time.time()
print('Time cost = %fs' % (time_end - time_start))

Time cost = 1.764140s


In [24]:
time_start = time.time()
for i in range(len(df_1226)):
    if '中传' in df_1226.iloc[i,16]:
        df_1226.iloc[i,17] = 1
                
time_end = time.time()
print('Time cost = %fs' % (time_end - time_start))

Time cost = 1.763059s


In [25]:
time_start = time.time()
for i in range(len(df_1226)):
    if '北影' in df_1226.iloc[i,16]:
        df_1226.iloc[i,17] = 1
                
time_end = time.time()
print('Time cost = %fs' % (time_end - time_start))

Time cost = 1.762273s


In [26]:
time_start = time.time()
for i in range(len(df_1226)):
    if '北电' in df_1226.iloc[i,16]:
        df_1226.iloc[i,17] = 1
                
time_end = time.time()
print('Time cost = %fs' % (time_end - time_start))

Time cost = 1.786829s


In [28]:
time_start = time.time()
for i in range(len(df_1226)):
    if '美院' in df_1226.iloc[i,16]:
        df_1226.iloc[i,17] = 1
                
time_end = time.time()
print('Time cost = %fs' % (time_end - time_start))

Time cost = 1.790943s


In [30]:
df_1226['是否是美术类/艺术类学校毕业'].value_counts()

0    108020
1      5661
Name: 是否是美术类/艺术类学校毕业, dtype: int64

In [31]:
df_1226['是否是美术类/艺术类学校毕业'].to_excel(r'/Users/ichigo34/Downloads/2.招生数据分析项目/回归分析/是否是艺术学校毕业的.xlsx', index = False)